#ifndef _INCLUDE_VERSION_INFORMATION_H_
#define _INCLUDE_VERSION_INFORMATION_H_

/**
 * @file Contains version information.
 * @brief This file will redirect to an autogenerated version if being compiled via
 * the build scripts.
 */

#if defined SM_GENERATED_BUILD
#include <sourcemod_version_auto.h>
#define BINARY_NAME "vphysics.ext.2.css.dll\0"
// Map platform auto-gen macros to the names expected by version.rc & smsdk_config.h
#define SM_FILE_VERSION		SM_VERSION_FILE
#define SM_FULL_VERSION		SM_VERSION_STRING
#define SM_VERSION			SM_BUILD_MAJOR "." SM_BUILD_MINOR "." SM_BUILD_RELEASE
#define SM_BUILD_UNIQUEID	SM_BUILD_LOCAL_REV ":" SM_BUILD_CSET
#else

#ifndef SM_GENERATED_BUILD
#undef BINARY_NAME
#define BINARY_NAME "vphysics.ext.dll\0"
#endif

#define SM_BUILD_TAG		"-manual"
#define SM_BUILD_UNIQUEID	"[MANUAL BUILD]"
#define SM_VERSION			"1.0.0"
#define SM_FULL_VERSION		SM_VERSION SM_BUILD_TAG
#define SM_FILE_VERSION		1,0,0,0

#endif

#endif /* _INCLUDE_VERSION_INFORMATION_H_ */
